#Use Python 3.6 as a base image
FROM python:3.7
WORKDIR /servicefour
# Copy contents into image
COPY requirements.txt .
# install pip dependencies from requirements file
RUN pip3 install -r requirements.txt
# Expose correct port
COPY . .
EXPOSE 5003
# Create an entrypoint
ENTRYPOINT ["python", "app.py"]