pipeline {
    agent any
    environment{
        DATABASE_URI = credentials('DATABASE_URI')
        app_version = 'version1'
    }
    stages{

        stage('Stage 0: Build'){
            steps{
                dir('projectwo') {
                sh "docker-compose build"
  
            }

            }
        }

        stage('Stage 1: Test'){
            steps{
                sh "bash pytest.sh"
                
            }
        }

        stage('Stage 2: Tag & Push Image'){
                steps{
                        sh 'docker-compose push'
                        
                    }
                }

        stage('Stage 3: configuration management'){
                steps{
                       sh 'cd playbook && ansible-playbook -i inventory.yaml playbook.yaml' 
                        }
                    }

        stage('Stage 4: Deploy'){
            steps{
                sh " docker stack deploy --compose-file docker-compose.yaml projectwo"
            }
        }
    }
}

